name: grid_creator
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.3.2=h166bdaf_0
  - attrs=24.2.0=pyh71513ae_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.14.6=py38ha65f79e_0
  - cfitsio=3.470=hb418390_7
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - curl=7.86.0=h7bff187_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - decorator=4.4.2=py_0
  - descartes=1.1.0=py_4
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fiona=1.8.20=py38ha695d3a_1
  - folium=0.18.0=pyhd8ed1ab_0
  - fontconfig=2.14.2=h14ed4e7_0
  - freetype=2.12.1=h267a509_2
  - freexl=1.0.6=h166bdaf_1
  - gdal=3.3.0=py38h507a4fd_1
  - geoalchemy2=0.6.3=py_0
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.13.2=pyhd8ed1ab_1
  - geopandas-base=0.13.2=pyha770c72_1
  - geopy=2.1.0=pyhd3deb0d_0
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=hcf90da6_5
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.10=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json-c=0.15=h98cffda_0
  - kealib=1.4.14=hcc255d8_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libblas=3.9.0=20_linux64_openblas
  - libboost-headers=1.88.0=ha770c72_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.86.0=h7bff187_1
  - libdap4=3.20.6=hd7c4107_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.3=h58526e2_2
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgdal=3.3.0=h679344c_1
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.68.4=h3e27bee_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libkml=1.3.0=h01aab08_1018
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopus=1.5.2=hd0c01bc_0
  - libpng=1.6.43=h2797004_0
  - libpq=13.5=hd57d9b9_1
  - librttopo=1.1.0=h1185371_6
  - libspatialindex=2.0.0=he02047a_0
  - libspatialite=5.0.1=h20cb978_4
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.2.0=hbd63e13_2
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.13=h4ab18f5_6
  - linecache2=1.0.0=py_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.4.2=py38h578d9bd_0
  - matplotlib-base=3.4.2=py38hf4fb855_0
  - munch=4.0.0=pyhd8ed1ab_0
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - ncurses=6.5=h2d0b736_3
  - networkx=2.5.1=pyhd8ed1ab_0
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1w=hd590300_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.2.4=py38h1abd341_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pixman=0.46.0=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - poppler=21.03.0=h93df280_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=13.5=h2510834_1
  - proj=8.0.0=h277dcde_0
  - psycopg2=2.9.2=py38h497a2fe_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyproj=3.0.1=py38hdf83a33_1
  - pyqt=5.12.3=py38h578d9bd_8
  - pyqt-impl=5.12.3=py38h0ffb2e6_8
  - pyqt5-sip=4.19.18=py38h709712a_8
  - pyqtchart=5.12=py38h7400c14_8
  - pyqtwebengine=5.12.1=py38h7400c14_8
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.4=pyhd8ed1ab_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - qt=5.12.9=hda022c4_4
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_0
  - rtree=1.3.0=py38h00415a3_1
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.3.24=py38h0a891b7_1
  - sqlite=3.46.0=h6d4b2fc_0
  - statsmodels=0.14.1=py38h7f0c24c_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.2.9=h91fcb0e_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38hfb59056_0
  - traceback2=1.4.0=pyhd8ed1ab_1
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h78e105d_0
  - unittest2=1.1.0=py38_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h9d8b166_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.4.9=ha95c52a_0
  - pip:
      - affine==2.4.0
      - argparse==1.4.0
      - asttokens==3.0.0
      - backcall==0.2.0
      - backports-tarfile==1.2.0
      - blosc2==2.0.0
      - contextily==1.2.0
      - cryptography==44.0.3
      - cython==3.0.12
      - egoio==0.4.8
      - executing==2.2.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jsonpickle==4.0.5
      - keyring==25.5.0
      - keyrings-alt==5.0.2
      - matplotlib-inline==0.1.7
      - mercantile==1.2.1
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - numexpr==2.8.6
      - numpy==1.21.6
      - oedialect==0.0.10
      - osmnx==1.1.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - ply==3.11
      - prompt-toolkit==3.0.51
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.1
      - pymetis==2023.1.1
      - pyomo==6.8.2
      - pypsa==0.17.1
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - rasterio==1.3.11
      - saio==0.2.1
      - scikit-learn==0.24.2
      - scipy==1.7.3
      - secretstorage==3.3.3
      - setuptools==57.4.0
      - shapely==1.8.5.post1
      - snuggs==1.4.7
      - stack-data==0.6.3
      - tables==3.8.0
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - wcwidth==0.2.13
      - zipp==3.20.2
prefix: /home/matthiasbehr/miniconda3/envs/grid_creator
