name: grid_creator
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - blosc=1.21.6=he440d0b_1
  - bottleneck=1.5.0=py312hc0a28a1_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py312h2ec8cdc_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.19.0=h3122c55_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cartopy=0.24.0=py312hf9745cd_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - cftime=1.6.4=py312hc0a28a1_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py312h68727a3_0
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dask-core=2025.5.1=pyhd8ed1ab_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.58.4=py312h178313f_0
  - freetype=2.13.3=ha770c72_1
  - freexl=2.0.0=h9dce30a_2
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - geopandas=1.1.1=pyhd8ed1ab_0
  - geopandas-base=1.1.1=pyha770c72_0
  - geos=3.13.1=h97f6797_0
  - giflib=5.2.2=hd590300_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h2d575fe_101
  - highspy=1.11.0=np20py312ha7205f5_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.1=gpl_h98cc613_100
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgdal-core=3.11.0=h5e6393a_5
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgomp=15.1.0=h767d61c_3
  - libhwy=1.2.0=hf40a0c7_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h7b0646d_2
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h0134ee8_117
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libpng=1.6.49=h943b412_0
  - librttopo=1.1.0=hd718a1a_18
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.50.1=h6cd9bfd_7
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - linopy=0.5.5=pyhd8ed1ab_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - markupsafe=3.0.2=py312h178313f_1
  - minizip=4.0.10=h05a5f5f_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - narwhals=1.44.0=pyhe01879c_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.2=nompi_py312h3805cb1_102
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.10.2=py312h6a710ac_100
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pillow=11.2.1=py312h80c1187_0
  - pip=25.1.1=pyh8b19718_0
  - plotly=6.1.2=pyhd8ed1ab_0
  - polars=1.31.0=default_h1650462_0
  - polars-default=1.31.0=py39hfac2b71_0
  - proj=9.6.2=h0054346_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pyogrio=0.11.0=py312h5426b81_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pypsa=0.35.0=pyhd8ed1ab_0
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py312h09a4e84_6
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-gil=3.12.11=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=7_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - requests=2.32.4=pyhd8ed1ab_0
  - scikit-learn=1.7.0=py312h7a48858_1
  - scipy=1.15.2=py312ha707e6e_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sqlite=3.50.1=hb7a22d2_7
  - statsmodels=0.14.4=py312hc0a28a1_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - validators=0.35.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xerces-c=3.2.5=h988505b_2
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - cdsapi==0.7.6
      - comm==0.2.3
      - cryptography==45.0.6
      - debugpy==1.8.15
      - decorator==4.4.2
      - defusedxml==0.7.1
      - ecmwf-datastores-client==0.4.0
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - git-filter-repo==2.47.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - iniconfig==2.1.0
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.2.1
      - jedi==0.19.2
      - jeepney==0.9.0
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keyring==25.6.0
      - lark==1.2.2
      - lxml==6.0.0
      - mapclassify==2.4.3
      - mastr-data-processor==1.0.0
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - more-itertools==10.7.0
      - multiurl==0.3.7
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.5.1
      - nose==1.3.7
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numpy==1.26.0
      - open-mastr==0.15.0
      - openpyxl==3.1.2
      - osmnx==2.0.4
      - overrides==7.7.0
      - pandas==2.1.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycity-base==0.3.3
      - pygments==2.19.2
      - pyproj==3.6.1
      - pytest==8.4.1
      - pytest-mpl==0.17.0
      - python-json-logger==3.3.0
      - pyzmq==27.0.1
      - referencing==0.36.2
      - requests-file==2.1.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - richardsonpy==0.2.1
      - rpds-py==0.26.0
      - secretstorage==3.3.3
      - send2trash==1.8.3
      - shapely==2.0.1
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.43
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tornado==6.5.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20250708
      - uesgraphs==0.6.4
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - xlrd==2.0.2
      - xmltodict==0.14.2
      - zeep==4.3.1
prefix: /home/matthiasbehr/miniconda3/envs/grid_creator
